// <auto-generated />
namespace HighscoreService.Migrations

open Models
open System
open System.Collections.Generic
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Migrations.Operations
open Microsoft.EntityFrameworkCore.Migrations.Operations.Builders
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata


[<DbContext(typeof<HighscoresContext>)>]
[<Migration("20200311173540_fixUserTable")>]
type fixUserTable() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropForeignKey(
            name = "FK_Score_User_userId"
            , table = "Score") |> ignore

        migrationBuilder.DropPrimaryKey(
            name = "PK_User"
            , table = "User") |> ignore

        migrationBuilder.DropPrimaryKey(
            name = "PK_Score"
            , table = "Score") |> ignore

        migrationBuilder.RenameTable(
            name = "User"
            , newName = "Users", newSchema = null) |> ignore

        migrationBuilder.RenameTable(
            name = "Score"
            , newName = "Scores", newSchema = null) |> ignore

        migrationBuilder.RenameIndex(
            name = "IX_Score_userId"
            , table = "Scores", newName = "IX_Scores_userId") |> ignore

        migrationBuilder.AddPrimaryKey(
            name = "PK_Users"
            , table = "Users", column = "id") |> ignore

        migrationBuilder.AddPrimaryKey(
            name = "PK_Scores"
            , table = "Scores", column = "id") |> ignore

        migrationBuilder.AddForeignKey(
            name = "FK_Scores_Users_userId"
            , table = "Scores", column = "userId", principalTable = "Users", principalColumn = "id", onDelete = ReferentialAction.Cascade) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropForeignKey(
            name = "FK_Scores_Users_userId"
            , table = "Scores") |> ignore

        migrationBuilder.DropPrimaryKey(
            name = "PK_Users"
            , table = "Users") |> ignore

        migrationBuilder.DropPrimaryKey(
            name = "PK_Scores"
            , table = "Scores") |> ignore

        migrationBuilder.RenameTable(
            name = "Users"
            , newName = "User", newSchema = null) |> ignore

        migrationBuilder.RenameTable(
            name = "Scores"
            , newName = "Score", newSchema = null) |> ignore

        migrationBuilder.RenameIndex(
            name = "IX_Scores_userId"
            , table = "Score", newName = "IX_Score_userId") |> ignore

        migrationBuilder.AddPrimaryKey(
            name = "PK_User"
            , table = "User", column = "id") |> ignore

        migrationBuilder.AddPrimaryKey(
            name = "PK_Score"
            , table = "Score", column = "id") |> ignore

        migrationBuilder.AddForeignKey(
            name = "FK_Score_User_userId"
            , table = "Score", column = "userId", principalTable = "User", principalColumn = "id", onDelete = ReferentialAction.Cascade) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
            .HasAnnotation("ProductVersion", "2.2.6-servicing-10079") |> ignore

        modelBuilder.Entity("Models.Score", (fun b ->

            b.Property<int>("id")
                .ValueGeneratedOnAdd() |> ignore

            b.Property<int>("userId")
                .IsRequired() |> ignore

            b.Property<int>("value")
                .IsRequired() |> ignore


            b.HasKey("id") |> ignore


            b.HasIndex("userId") |> ignore


            b.ToTable("Scores") |> ignore
        )) |> ignore

        modelBuilder.Entity("Models.User", (fun b ->

            b.Property<int>("id")
                .ValueGeneratedOnAdd() |> ignore

            b.Property<string>("name") |> ignore


            b.HasKey("id") |> ignore


            b.ToTable("Users") |> ignore
        )) |> ignore

        modelBuilder.Entity("Models.Score", (fun b ->

            b.HasOne("Models.User", "user")
                .WithMany("scores")
                .HasForeignKey("userId")
                .OnDelete(DeleteBehavior.Cascade)|> ignore
        )) |> ignore

